; PlatformIO Project Configuration File

[env:m5stack-stamps3]
platform = espressif32@6.3.1
board = m5stack-stamps3
framework = arduino
lib_deps = 
	m5stack/M5Unified@^0.2.14
	meganetaaan/M5Stack-Avatar@^0.10.0
lib_ldf_mode = deep+
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D SCK=13
	-D MISO=11
	-D MOSI=15
	-D SS=12
upload_speed = 115200
build_src_filter = +<crawler_main.cpp>

[env:m5stick-c-plus2]
platform = espressif32@6.3.1
board = m5stick-c
framework = arduino
lib_deps = 
    m5stack/M5Unified@^0.2.14
build_src_filter = +<controller_main.cpp> +<M5HatMiniJoyC.cpp>

[env:m5stack-cores3-stackchan]
platform = espressif32
board = m5stack-cores3
framework = arduino
lib_deps =
    m5stack/M5Unified@^0.2.14
    meganetaaan/M5Stack-Avatar@^0.10.0
    https://github.com/m5stack/StackChan-BSP.git
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<stackchan_main.cpp>
